THIS_SRCS = bdos.c bdosptr.s delay.c fexistp.c getcbrk.c getdate.c getdfree.c \
	getdinfo.c getdos_v.c getftime.c gettime.c gettimeo.c \
	osflavor.c osmajor.c osminor.c remotdrv.c \
	remothdl.c setcbrk.c setdate.c setftime.c settime.c

include $(MENUET_LIBC_TOPDIR)/Make.rules
