include '../../trunk/editbox.mac'
include '../../trunk/checkbox.mac'
include '../../trunk/optionbox.mac'

macro get_sys_colors col_buf
{
        ;mov     eax,48
        push    48
        pop     eax
        ;mov     ebx,3
        push    3
        pop     ebx
        ;mov     ecx,col_buf
        push    col_buf
        pop     ecx
        ;mov     edx,40
        push    40
        pop     edx
        mcall
}

