THIS_SRCS = ct_flags.c ct_lower.c ct_upper.c isalnum.c isalpha.c isascii.c \
	iscntrl.c isdigit.c isgraph.c islower.c isprint.c ispunct.c \
	isspace.c isupper.c isxdigit.c toascii.c tolower.c toupper.c

include $(MENUET_LIBC_TOPDIR)/Make.rules
