fasm __lib__.asm
fasm abs.asm
fasm acos.asm
fasm acosh.asm
fasm asin.asm
fasm asinh.asm
fasm atan.asm
fasm atan2.asm
fasm atanh.asm
fasm atoi.asm
fasm atol.asm
fasm atoll.asm
fasm calloc.asm
fasm ceil.asm
fasm clearerr.asm
fasm closedir.asm
fasm cos.asm
fasm cosh.asm
fasm debug_printf.asm
fasm difftime.asm
fasm div.asm
fasm exit.asm
fasm exp.asm
fasm fabs.asm
fasm fclose.asm
fasm feof.asm
fasm ferror.asm
fasm fflush.asm
fasm fgetc.asm
fasm fgetpos.asm
fasm fgets.asm
fasm floor.asm
fasm fmod.asm
fasm fopen.asm
fasm fputc.asm
fasm fputs.asm
fasm fread.asm
fasm free.asm
fasm freopen.asm
fasm frexp.asm
fasm fseek.asm
fasm fsetpos.asm
fasm ftell.asm
fasm fwrite.asm
fasm getchar.asm
fasm gets.asm
fasm hypot.asm
fasm labs.asm
fasm ldexp.asm
fasm ldiv.asm
fasm llabs.asm
fasm lldiv.asm
fasm localtime.asm
fasm log.asm
fasm malloc.asm
fasm memccpy.asm
fasm memchr.asm
fasm memcmp.asm
fasm memcpy.asm
fasm memmove.asm
fasm memset.asm
fasm mktime.asm
fasm modf.asm
fasm modfl.asm
fasm opendir.asm
fasm perror.asm
fasm pow.asm
fasm pow10.asm
fasm pow2.asm
fasm printf.asm
fasm puts.asm
fasm readdir.asm
fasm realloc.asm
fasm remove.asm
fasm rename.asm
fasm rewind.asm
fasm rewinddir.asm
fasm seekdir.asm
fasm setbuf.asm
fasm setvbuf.asm
fasm sin.asm
fasm sinh.asm
fasm snprintf.asm
fasm sprintf.asm
fasm sqrt.asm
fasm strcat.asm
fasm strchr.asm
fasm strcmp.asm
fasm strcoll.asm
fasm strcpy.asm
fasm strcspn.asm
fasm strerror.asm
fasm strlen.asm
fasm strncat.asm
fasm strncmp.asm
fasm strncpy.asm
fasm strpbrk.asm
fasm strrchr.asm
fasm strrev.asm
fasm strspn.asm
fasm strstr.asm
fasm strtok.asm
fasm strxfrm.asm
fasm tan.asm
fasm tanh.asm
fasm telldir.asm
fasm time.asm
fasm tmpfile.asm
fasm tmpnam.asm
fasm vprintf.asm
fasm vsnprintf.asm
kos32-ar -ru liblibc.obj.a *.o
del *.o
pause