THIS_SRCS = acosh.c acos.s asinh.c asin.s atan2.s atanh.c atan.s \
	ceil.s cosh.c cos.s exp.s fabs.s floor.s fmod.s frexp.c huge_val.c \
	hypot.c ldexp.c log.s modfl.s modf.s pow10.s pow2.s pow.s sinh.c \
	sin.s sqrt.s tanh.c tan.s

include $(MENUET_LIBC_TOPDIR)/Make.rules
