# SPDX-License-Identifier: GPL-2.0-only
#
# Atlas converter for the Dino game: PNG -> palette-indexed C header.
# The final binary is kpack-compressed, so the flat index array costs
# about the same on disk as any pre-compressed encoding would.
#
# Usage: python png2h.py sprites100.png sprites.h

import os
import sys

from PIL import Image

# Regions the game never draws (moon and stars: night mode is not implemented)
BLANK = [(482, 0, 654, 53)]

def main():
    src, dst = sys.argv[1], sys.argv[2]
    img = Image.open(src).convert("RGBA")
    w, h = img.size
    pixels = list(img.getdata())

    opaque = [None if a == 0 else (r, g, b) for r, g, b, a in pixels]
    for x0, y0, x1, y1 in BLANK:
        for y in range(y0, y1 + 1):
            for x in range(x0, x1 + 1):
                opaque[y * w + x] = None

    # Transparent -> 0, remaining colors by frequency -> 1..N
    freq = {}
    for c in opaque:
        if c is not None:
            freq[c] = freq.get(c, 0) + 1
    colors = sorted(freq, key=freq.get, reverse=True)
    index = {c: i + 1 for i, c in enumerate(colors)}
    data = [0 if c is None else index[c] for c in opaque]

    with open(dst, "w", newline="\n") as f:
        f.write("// Generated by png2h.py from %s - do not edit\n" % os.path.basename(src))
        f.write("#pragma once\n\n")
        f.write("#define ATLAS_WIDTH  %d\n" % w)
        f.write("#define ATLAS_HEIGHT %d\n\n" % h)
        f.write("// Index 0 is transparent\n")
        f.write("static const unsigned DINO_PALETTE[%d] = {\n    0x00000000," % (len(colors) + 1))
        for r, g, b in colors:
            f.write(" 0x00%02X%02X%02X," % (r, g, b))
        f.write("\n};\n\n")
        f.write("static const unsigned char SPRITE_ATLAS[ATLAS_WIDTH * ATLAS_HEIGHT] = {\n")
        for y in range(h):
            row = data[y * w:(y + 1) * w]
            f.write("    " + ",".join(str(v) for v in row) + ",\n")
        f.write("};\n")

    print(f"atlas {w}x{h}, {len(colors)} colors + transparent, {len(data)} bytes")

if __name__ == "__main__":
    main()
