/* This file is automatically generated by mkversion. */
/* Please do not modify it unless you know what you are doing. */
#define MENUET_LIBC_VERSION "0.2.9"

#ifdef INCLUDE_RCS_ID
static const char * ___menuet__libc_version_0_2_9="MenuetOS GNU C library port by Jarek Pelczar. This file is " __FILE__ ; 
#endif
