# Path to /programs
SVN_PROGR:=../../..

# Path to /programs/bcc32
SVN_BCC32:=$(SVN_PROGR)/bcc32

# Path to t2fasm
T2FASM:=$(SVN_BCC32)/t2fasm

# Path to include
INCLUDE:=$(SVN_BCC32)/include

# Path to Bin folder
KOS32_BCC:=/home/autobuild/borlandcpp/bin

# Filename without .cpp
FILENAME:=color_dlg

include $(SVN_BCC32)/Makefile_app
