# This is the makefile in kolibrios/contrib/network/netsurf/libcss
# Need to add recursive calling to all the subdirectories. For now, use the generated .a file for testing.

OUTFILE := $(CURDIR)/libhubbub.a

OBJS = $(wildcard hubbub/libo.o)

include $(MENUETDEV)/makefiles/Makefile_for_lib
