# This is the makefile in kolibrios/contrib/network/netsurf/libnsbmp/src
# Need to add recursive calling to all the subdirectories. For now, use the generated .a file for testing.

OUTFILE := $(CURDIR)/libnsbmp.a

OBJS = $(wildcard *.o)

include $(MENUETDEV)/makefiles/Makefile_for_lib
