THIS_SRCS = access.c alarm.c chdir.c chown.c close.c ctermid.c dup2.c \
	dup.c execl.c execle.c execlp.c execlpe.c execv.c execve.c execvp.c \
	execvpe.c fork.c fpathcon.c getcwd.c getegid.c geteuid.c getgid.c \
	getgroup.c getlogin.c getopt.c getpgrp.c getpid.c getppid.c getuid.c \
	isatty.c link.c lseek.c pathconf.c pause.c pipe.c read.c rmdir.c setgid.c \
	setpgid.c setsid.c setuid.c sleep.c sysconf.c ttyname.c unlink.s write.c

include $(MENUET_LIBC_TOPDIR)/Make.rules
