CC=gcc
NAME=kos32-tcc

SRC=libtcc.c tcc.c
CFLAGS= -DTCC_TARGET_MEOS_LINUX 
LFLAGS= -m32

all:
	$(CC) $(CFLAGS) $(LFLAGS) $(SRC) -o $(NAME) 
install: 
	cp $(NAME) ../bin 
compress:
	upx $(NAME)
clean:
	rm -f $(NAME)
