all:
	make -C compat
	make -C dir
	make -C dos
	make -C dos_emu
	make -C errno
	make -C io
	make -C process
	make -C sys

clean:
	make -C compat clean
	make -C dir clean
	make -C dos clean
	make -C dos_emu clean
	make -C errno clean
	make -C io clean
	make -C process clean
	make -C sys clean

depend:
	make -C compat depend
	make -C dir depend
	make -C dos depend
	make -C dos_emu depend
	make -C errno depend
	make -C io depend
	make -C process depend
	make -C sys depend
