
OUTFILE = libo.o
OBJS = stylesheet.o
CFLAGS += -I ../../libwapcaplet/include/ -I ../../libparserutils/include/ -I ../include/ -I ../../ -I ./ -I /home/sourcerer/kos_src/newenginek/kolibri/include

include $(MENUETDEV)/makefiles/Makefile_for_o_lib
