KTCC_DIR = ../../develop/ktcc/trunk

NAME = man2html

KTCC = kos32-tcc
KPACK = kpack

SRC = man2html.c cgibase.c abbrev.c strdefs.c

CFLAGS = -D_KOLIBRI -DNOCGI -I$(KTCC_DIR)/libc.obj/include -I inc
LFLAGS = -nostdlib -L$(KTCC_DIR)/bin/lib $(KTCC_DIR)/bin/lib/crt0.o
LIBS = -ltcc -lc.obj

all:
	$(KTCC) $(CFLAGS) $(SRC) $(LFLAGS) $(LIBS) -o $(NAME)
	$(KPACK) $(NAME)

clean:
	rm $(NAME)
