/* DGen font, generated by pbm2df from "dgenfont_7x5.pbm" */

#include <stdio.h> /* for NULL definition */

static const short _glyph_20[] = {-1};
static const short _glyph_21[] = {2, 7, 7, 14, -1};
static const short _glyph_22[] = {1, 2, 5, 2, -1};
static const short _glyph_23[] = {1, 2, 4, 1, 1, 1, 1, 4, 2, 4, 1, 1, 1, 1, 4, 2, -1};
static const short _glyph_24[] = {1, 1, 1, 1, 3, 2, 6, 1, 1, 6, 2, 3, 1, 1, 1, -1};
static const short _glyph_25[] = {0, 1, 3, 3, 1, 2, 6, 6, 2, 1, 3, 3, 1, -1};
static const short _glyph_26[] = {1, 6, 2, 6, 1, 2, 3, 3, 5, 1, 2, -1};
static const short _glyph_27[] = {2, 7, -1};
static const short _glyph_28[] = {3, 6, 7, 7, 8, -1};
static const short _glyph_29[] = {1, 8, 7, 7, 6, -1};
static const short _glyph_2A[] = {2, 5, 2, 2, 4, 1, 1, 4, 2, 2, 5, -1};
static const short _glyph_2B[] = {9, 6, 1, 1, 6, -1};
static const short _glyph_2C[] = {23, 6, -1};
static const short _glyph_2D[] = {15, 1, 1, -1};
static const short _glyph_2E[] = {30, -1};
static const short _glyph_2F[] = {4, 6, 6, 6, 6, -1};
static const short _glyph_30[] = {1, 1, 1, 4, 4, 3, 2, 2, 3, 4, 4, 1, 1, -1};
static const short _glyph_31[] = {2, 6, 1, 7, 7, 6, 1, 1, -1};
static const short _glyph_32[] = {1, 1, 1, 4, 3, 6, 6, 6, 1, 1, 1, -1};
static const short _glyph_33[] = {0, 1, 1, 1, 8, 5, 1, 8, 3, 1, 1, 1, -1};
static const short _glyph_34[] = {3, 6, 1, 5, 2, 4, 1, 1, 1, 7, -1};
static const short _glyph_35[] = {0, 1, 1, 1, 1, 3, 7, 1, 1, 1, 1, 7, 3, 1, 1, 1, 1, -1};
static const short _glyph_36[] = {0, 1, 1, 1, 1, 3, 7, 1, 1, 1, 1, 3, 4, 3, 1, 1, 1, 1, -1};
static const short _glyph_37[] = {0, 1, 1, 1, 1, 6, 6, 6, 6, -1};
static const short _glyph_38[] = {1, 1, 1, 4, 4, 4, 1, 1, 4, 4, 4, 1, 1, -1};
static const short _glyph_39[] = {0, 1, 1, 1, 1, 3, 4, 3, 1, 1, 1, 1, 7, 3, 1, 1, 1, 1, -1};
static const short _glyph_3A[] = {9, 21, -1};
static const short _glyph_3B[] = {9, 14, 6, -1};
static const short _glyph_3C[] = {3, 6, 6, 8, 8, -1};
static const short _glyph_3D[] = {8, 1, 1, 12, 1, 1, -1};
static const short _glyph_3E[] = {1, 8, 8, 6, 6, -1};
static const short _glyph_3F[] = {1, 1, 1, 7, 6, 14, -1};
static const short _glyph_40[] = {1, 1, 1, 4, 2, 2, 3, 2, 1, 1, 3, 8, 1, 1, 1, -1};
static const short _glyph_41[] = {1, 1, 1, 4, 4, 3, 1, 1, 1, 1, 3, 4, 3, 4, -1};
static const short _glyph_42[] = {0, 1, 1, 1, 4, 4, 3, 2, 1, 4, 4, 3, 1, 1, 1, -1};
static const short _glyph_43[] = {1, 1, 1, 1, 3, 7, 7, 8, 1, 1, 1, -1};
static const short _glyph_44[] = {0, 1, 1, 1, 4, 4, 3, 4, 3, 4, 3, 1, 1, 1, -1};
static const short _glyph_45[] = {1, 1, 1, 1, 3, 7, 1, 1, 1, 1, 3, 8, 1, 1, 1, -1};
static const short _glyph_46[] = {1, 1, 1, 4, 7, 1, 1, 1, 4, 7, -1};
static const short _glyph_47[] = {1, 1, 1, 1, 3, 7, 2, 1, 1, 3, 4, 4, 1, 1, -1};
static const short _glyph_48[] = {0, 4, 3, 4, 3, 1, 1, 1, 1, 3, 4, 3, 4, -1};
static const short _glyph_49[] = {1, 1, 1, 6, 7, 7, 6, 1, 1, -1};
static const short _glyph_4A[] = {0, 1, 1, 1, 8, 7, 3, 4, 4, 1, 1, -1};
static const short _glyph_4B[] = {0, 3, 4, 2, 5, 1, 6, 2, 5, 3, -1};
static const short _glyph_4C[] = {0, 7, 7, 7, 7, 1, 1, 1, 1, -1};
static const short _glyph_4D[] = {0, 4, 3, 1, 2, 1, 3, 2, 2, 3, 4, 3, 4, -1};
static const short _glyph_4E[] = {0, 4, 3, 1, 3, 3, 2, 2, 3, 3, 1, 3, 4, -1};
static const short _glyph_4F[] = {1, 1, 1, 4, 4, 3, 4, 3, 4, 4, 1, 1, -1};
static const short _glyph_50[] = {0, 1, 1, 1, 4, 4, 3, 1, 1, 1, 4, 7, -1};
static const short _glyph_51[] = {1, 1, 1, 4, 4, 3, 2, 2, 3, 3, 1, 4, 1, 1, 1, -1};
static const short _glyph_52[] = {1, 1, 1, 4, 4, 3, 2, 1, 4, 3, 4, 4, -1};
static const short _glyph_53[] = {1, 1, 1, 1, 3, 8, 1, 1, 8, 3, 1, 1, 1, -1};
static const short _glyph_54[] = {0, 1, 1, 1, 1, 5, 7, 7, 7, -1};
static const short _glyph_55[] = {0, 4, 3, 4, 3, 4, 3, 4, 4, 1, 1, -1};
static const short _glyph_56[] = {0, 4, 3, 4, 4, 2, 5, 2, 6, -1};
static const short _glyph_57[] = {0, 4, 3, 4, 3, 2, 2, 3, 2, 2, 4, 1, 1, -1};
static const short _glyph_58[] = {0, 4, 4, 2, 6, 6, 2, 4, 4, -1};
static const short _glyph_59[] = {0, 4, 4, 2, 6, 7, 7, -1};
static const short _glyph_5A[] = {0, 1, 1, 1, 1, 6, 6, 6, 6, 1, 1, 1, 1, -1};
static const short _glyph_5B[] = {2, 1, 6, 7, 7, 7, 1, -1};
static const short _glyph_5C[] = {0, 8, 8, 8, 8, -1};
static const short _glyph_5D[] = {1, 1, 7, 7, 7, 6, 1, -1};
static const short _glyph_5E[] = {2, 6, 2, 4, 4, -1};
static const short _glyph_5F[] = {28, 1, 1, 1, 1, -1};
static const short _glyph_60[] = {2, 7, -1};
static const short _glyph_61[] = {1, 1, 1, 4, 4, 3, 1, 1, 1, 1, 3, 4, 3, 4, -1};
static const short _glyph_62[] = {0, 1, 1, 1, 4, 4, 3, 2, 1, 4, 4, 3, 1, 1, 1, -1};
static const short _glyph_63[] = {1, 1, 1, 1, 3, 7, 7, 8, 1, 1, 1, -1};
static const short _glyph_64[] = {0, 1, 1, 1, 4, 4, 3, 4, 3, 4, 3, 1, 1, 1, -1};
static const short _glyph_65[] = {1, 1, 1, 1, 3, 7, 1, 1, 1, 1, 3, 8, 1, 1, 1, -1};
static const short _glyph_66[] = {1, 1, 1, 4, 7, 1, 1, 1, 4, 7, -1};
static const short _glyph_67[] = {1, 1, 1, 1, 3, 7, 2, 1, 1, 3, 4, 4, 1, 1, -1};
static const short _glyph_68[] = {0, 4, 3, 4, 3, 1, 1, 1, 1, 3, 4, 3, 4, -1};
static const short _glyph_69[] = {1, 1, 1, 6, 7, 7, 6, 1, 1, -1};
static const short _glyph_6A[] = {0, 1, 1, 1, 8, 7, 3, 4, 4, 1, 1, -1};
static const short _glyph_6B[] = {0, 3, 4, 2, 5, 1, 6, 2, 5, 3, -1};
static const short _glyph_6C[] = {0, 7, 7, 7, 7, 1, 1, 1, 1, -1};
static const short _glyph_6D[] = {0, 4, 3, 1, 2, 1, 3, 2, 2, 3, 4, 3, 4, -1};
static const short _glyph_6E[] = {0, 4, 3, 1, 3, 3, 2, 2, 3, 3, 1, 3, 4, -1};
static const short _glyph_6F[] = {1, 1, 1, 4, 4, 3, 4, 3, 4, 4, 1, 1, -1};
static const short _glyph_70[] = {0, 1, 1, 1, 4, 4, 3, 1, 1, 1, 4, 7, -1};
static const short _glyph_71[] = {1, 1, 1, 4, 4, 3, 2, 2, 3, 3, 1, 4, 1, 1, 1, -1};
static const short _glyph_72[] = {1, 1, 1, 4, 4, 3, 2, 1, 4, 3, 4, 4, -1};
static const short _glyph_73[] = {1, 1, 1, 1, 3, 8, 1, 1, 8, 3, 1, 1, 1, -1};
static const short _glyph_74[] = {0, 1, 1, 1, 1, 5, 7, 7, 7, -1};
static const short _glyph_75[] = {0, 4, 3, 4, 3, 4, 3, 4, 4, 1, 1, -1};
static const short _glyph_76[] = {0, 4, 3, 4, 4, 2, 5, 2, 6, -1};
static const short _glyph_77[] = {0, 4, 3, 4, 3, 2, 2, 3, 2, 2, 4, 1, 1, -1};
static const short _glyph_78[] = {0, 4, 4, 2, 6, 6, 2, 4, 4, -1};
static const short _glyph_79[] = {0, 4, 4, 2, 6, 7, 7, -1};
static const short _glyph_7A[] = {0, 1, 1, 1, 1, 6, 6, 6, 6, 1, 1, 1, 1, -1};
static const short _glyph_7B[] = {2, 1, 6, 6, 1, 7, 7, 1, -1};
static const short _glyph_7C[] = {2, 7, 7, 7, 7, -1};
static const short _glyph_7D[] = {1, 1, 7, 7, 1, 6, 6, 1, -1};
static const short _glyph_7E[] = {8, 6, 2, 2, 6, -1};
static const short _glyph_7F[] = {-1};
const short *dgen_font_7x5[0x80] = {
  /* Fill in for the control characters */
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  _glyph_20,
  _glyph_21,
  _glyph_22,
  _glyph_23,
  _glyph_24,
  _glyph_25,
  _glyph_26,
  _glyph_27,
  _glyph_28,
  _glyph_29,
  _glyph_2A,
  _glyph_2B,
  _glyph_2C,
  _glyph_2D,
  _glyph_2E,
  _glyph_2F,
  _glyph_30,
  _glyph_31,
  _glyph_32,
  _glyph_33,
  _glyph_34,
  _glyph_35,
  _glyph_36,
  _glyph_37,
  _glyph_38,
  _glyph_39,
  _glyph_3A,
  _glyph_3B,
  _glyph_3C,
  _glyph_3D,
  _glyph_3E,
  _glyph_3F,
  _glyph_40,
  _glyph_41,
  _glyph_42,
  _glyph_43,
  _glyph_44,
  _glyph_45,
  _glyph_46,
  _glyph_47,
  _glyph_48,
  _glyph_49,
  _glyph_4A,
  _glyph_4B,
  _glyph_4C,
  _glyph_4D,
  _glyph_4E,
  _glyph_4F,
  _glyph_50,
  _glyph_51,
  _glyph_52,
  _glyph_53,
  _glyph_54,
  _glyph_55,
  _glyph_56,
  _glyph_57,
  _glyph_58,
  _glyph_59,
  _glyph_5A,
  _glyph_5B,
  _glyph_5C,
  _glyph_5D,
  _glyph_5E,
  _glyph_5F,
  _glyph_60,
  _glyph_61,
  _glyph_62,
  _glyph_63,
  _glyph_64,
  _glyph_65,
  _glyph_66,
  _glyph_67,
  _glyph_68,
  _glyph_69,
  _glyph_6A,
  _glyph_6B,
  _glyph_6C,
  _glyph_6D,
  _glyph_6E,
  _glyph_6F,
  _glyph_70,
  _glyph_71,
  _glyph_72,
  _glyph_73,
  _glyph_74,
  _glyph_75,
  _glyph_76,
  _glyph_77,
  _glyph_78,
  _glyph_79,
  _glyph_7A,
  _glyph_7B,
  _glyph_7C,
  _glyph_7D,
  _glyph_7E,
  _glyph_7F
};
