#!/bin/bash
set -e

AR=ar
FASM=fasm

set -e

cd $1

echo "Compile ASM files..."

rm -f *.o
cp __lib__.asm.bak __lib__.asm

for asm_file in $(find *.asm) 
do
    $FASM $asm_file >> /dev/null
done

echo "Create libc.obj.a library..."
ar -rsc ../lib/libc.obj.a *.o
rm -f *.asm *.o
echo "Done!"
