

VARIABLE   CSP    \ ”казатель стека контрол€

: CASE 
  CSP @ SP@ CSP ! ; IMMEDIATE

: ?OF_ 
  POSTPONE IF POSTPONE DROP ; IMMEDIATE

: OF 
  POSTPONE OVER POSTPONE = POSTPONE ?OF_ ; IMMEDIATE

: ENDOF 
  POSTPONE ELSE ; IMMEDIATE

: DUPENDCASE
  BEGIN SP@ CSP @ <> WHILE POSTPONE THEN REPEAT
  CSP ! ; IMMEDIATE

: ENDCASE 
  POSTPONE DROP   POSTPONE DUPENDCASE 
; IMMEDIATE

: OF\
  POSTPONE OVER POSTPONE <> POSTPONE IF ; IMMEDIATE

: OF;
  POSTPONE OVER POSTPONE = POSTPONE IF 2>R
  POSTPONE DUPENDCASE  2R>
  POSTPONE DROP ; IMMEDIATE

HEX
