OBJS := event.o dispatch.o event_target.o document_event.o \
		custom_event.o keyboard_event.o mouse_wheel_event.o \
		text_event.o event_listener.o mouse_event.o mutation_event.o \
		ui_event.o mouse_multi_wheel_event.o  mutation_name_event.o


OUTFILE = libo.o

CFLAGS += -I ../../include/ -I ../../ -I ../ -I ./ -I /home/sourcerer/kos_src/newenginek/kolibri/include
include $(MENUETDEV)/makefiles/Makefile_for_o_lib
