OBJS = IMG_bmp.o IMG.o IMG_gif.o IMG_jpg.o IMG_pcx.o IMG_png.o IMG_pnm.o \
	IMG_tga.o IMG_tif.o IMG_xcf.o IMG_xpm.o
OUTFILE = ../lib/libSDL_image.a
CFLAGS = -I../include -D_REENTRANT -DLOAD_BMP -DLOAD_GIF -DLOAD_JPG \
	-DLOAD_PCX -DLOAD_PNG -DLOAD_PNM -DLOAD_TGA -DLOAD_XPM

include $(MENUETDEV)/makefiles/Makefile_for_lib
