# Sources
OBJS := namespace.o hashtable.o character_valid.o validate.o

OUTFILE = libo.o

CFLAGS += -I ../../include/ -I ../../ -I ../ -I ./ -I /home/sourcerer/kos_src/newenginek/kolibri/include -I ../../../libwapcaplet/include/ -I ../../../libparserutils/include/
include $(MENUETDEV)/makefiles/Makefile_for_o_lib

