all:
	make -C cpu
	make -C endian
	make -C farptr
	make -C fpu
	make -C hwint
	make -C kb
	make -C sound
	make -C mem
	make -C timer

clean:
	make -C cpu clean
	make -C endian clean
	make -C farptr clean
	make -C fpu clean
	make -C hwint clean
	make -C kb clean
	make -C sound clean
	make -C mem clean
	make -C timer clean

depend:
	make -C cpu depend
	make -C endian depend
	make -C farptr depend
	make -C fpu depend
	make -C hwint depend
	make -C kb depend
	make -C sound depend
	make -C mem depend
	make -C timer depend

