#!/bin/bash

# Copyright maxcodehack, 2021
# gcc options for build for KolibriOS

# We start w/o param?
if [ -z "$*" ]
then
	echo -e "\033[1;31mfatal error: \033[0mno input files"
	exit 1
fi

# KLIBC variable exists?
if [ -z "$KLIBC" ]
then
	echo -e "\033[1;31mfatal error: \033[0mKLIBC variable not set"
	exit 1
fi

# GCC Flags for KolibriOS
FLAGS="-c -m32 -nostdinc -fno-common -fno-builtin -fno-leading-underscore -fno-pie -fno-stack-protector -fno-stack-check -mpreferred-stack-boundary=2"
KOS_PLATFORM="-Ulinux -U__linux -U__linux__ -U__gnu_linux__ -U__unix__ -U__unix -Uunix -Dkolibri -D__kolibri -D__kolibri__"

# And, execute gcc:
gcc $FLAGS $KOS_PLATFORM -I$KLIBC/source/include $*
