    win_face     equ 0xE1E1E1 ; - Фон обводки активного окна.                 ; 1
    win_inface   equ 0xE1E1E1 ; - Фон обводки неактивного окна.               ; 2
    win_frame    equ 0x204962 ; - Цвет внешней рамки активного окна.          ; 3
    win_inframe  equ 0xA1A1A1 ; - Цвет внешней рамки неактивного окна.        ; 4
    win_border   equ 0xE4DFE1 ; - Цвет внутренней рамки активного окна.       ; 5
    win_inborder equ 0xE4DFE1 ; - Цвет внутренней рамки неактивного окна.     ; 6
    win_body     equ 0xE4DFE1 ; - Фон клиентской части активного окна.        ; 7
    win_title    equ 0x2F2F2F ; - Цвет текста полосы заголовка.               ; 8
    win_text     equ 0x000000 ; - Цвет текста в рабочей области окна.         ; 9
    win_graytext equ 0x666666 ; - Цвет неактивного текста.                    ; 0
    menu_frame   equ 0x204962 ; - Цвет внешней рамки дочерних потоков         ; 1
    menu_body    equ 0xD4D4D4 ; - Фон дочерних потоков и меню приложения.     ; 2
    menu_text    equ 0x3C415B ; - Цвет текста дочерних потоков и меню.        ; 3
    panel_frame  equ 0x94AECE ; - Цвет внешней рамки панелей                  ; 4
    panel_body   equ 0xE4DFE1 ; - Фон панелей приложения.                     ; 5
    panel_text   equ 0x2F2F2F ; - Цвет текста панелей приложения.             ; 6
    hint_frame   equ 0x94AECE ; - Цвет внешней рамки подсказок                ; 7
    hint_body    equ 0xFAF8FA ; - Фон подсказки.                              ; 8
    hint_text    equ 0x3C415B ; - Цвет текста подсказки.                      ; 9
    btn_face     equ 0xEFEBEF ; - Фон кнопки.                                 ; 0
    btn_inface   equ 0xEFEBEF ; - Фон неактивной кнопки.                      ; 1
    btn_fcface   equ 0xEFEBEF ; - Фон кнопки при наведении.                   ; 2
    btn_frame    equ 0x7698C0 ; - Цвет рамки кнопки.                          ; 3
    btn_inframe  equ 0xB1B1B1 ; - Цвет рамки неактивной кнопки.               ; 4
    btn_fcframe  equ 0x5F86B6 ; - Цвет рамки кнопки при наведении.            ; 5
    btn_text     equ 0x373C42 ; - Цвет текста кнопки.                         ; 6
    btn_intext   equ 0xD0D9E8 ; - Цвет текста неактивной кнопки.              ; 7
    btn_fctext   equ 0x2D3135 ; - Цвет текста кнопки при наведении.           ; 8
    3d_face      equ 0xCED0D0 ; - Основной цвет наложения тени (скролл).      ; 9
    3d_dark      equ 0xD7D7D7 ; - Теневая обводка.                            ; 0
    3d_light     equ 0xFEFEFE ; - Световая обводка.                           ; 1
    gui_shadow   equ 0xFFFFFF ; - Цвет тени для неактивных элементов.         ; 2
    gui_face     equ 0xFAF8FA ; - Фон элементов.                              ; 3
    gui_inface   equ 0xF6F3F6 ; - Фон неактивных элементов.                   ; 4
    gui_fcface   equ 0xFAF8FA ; - Фон элементов при наведении.                ; 5
    gui_frame    equ 0x7698C0 ; - Рамка элемента.                             ; 6
    gui_inframe  equ 0xACACAC ; - Рамка неактивного элемента.                 ; 7
    gui_fcframe  equ 0x94AECE ; - Рамка элемента при наведении.               ; 8
    gui_text     equ 0x373C42 ; - Цвет текста элемента.                       ; 9
    gui_intext   equ 0x5F5F5F ; - Цвет текста неактивного элемента.           ; 0
    gui_fctext   equ 0x2F2F2F ; - Цвет текста элемента при наведении.         ; 1
    gui_select   equ 0xC7C9C9 ; - Цвет фона полосы выделения текста .         ; 2
    reserved     equ 0x000000 ; - Зарезервированно.                           ; 3




