-- Provides list of skins for distribution kit,
-- included by ../data/Tupfile.lua.
skinlist = {
"ConLenov/Aigul/Aigul.skn",
"ConLenov/Guzel/Guzel.skn",
"ConLenov/Guzel_magic/Guzel_magic.skn",
"ConLenov/FlowerMoon/FlowerMoon.skn",
"ConLenov/mntech/mntech.skn",
"ConLenov/LucidChocolate/LucidChocolate.skn",
"ConLenov/LucidCream/LucidCream.skn",
"ConLenov/Win10/Win10.skn",
"Leency/AreaSq/AreaSq.skn",
"Leency/Florence/Florence.skn",
"Leency/HydrogenOS/HydrogenOS.skn",
"Leency/Luna/Luna.skn",
"Leency/ObsidianOS/ObsidianOS.skn",
"Leency/Octo_flat/Octo_flat.skn",
"Leency/Shkvorka/Shkvorka.skn",
"Leency/Workbench/Workbench.skn",
"Leency/Yeah/Yeah.skn",
"maxcodehack/blacky/Blacky.skn",
"loggy/loggy.skn",
"night/night.skn",
"_old/5imple Alpha/2.5imple Alpha/2.5imple Alpha.skn",
"_old/5imple Alpha/3.5imple Alpha/3.5imple Alpha.skn",
"_old/black-glass/black-glass/black-glass.skn",
"_old/black-glass/black-glass_light/black-glass_light.skn",
"_old/blackskin/blackskin.skn",
"_old/Black_lace/2.Black_lace/2.Black_lace.skn",
"_old/Blended/Blended.skn",
"_old/cherry/cherry.skn",
"_old/CodeOpusC/Opus_A/Opus_A.skn",
"_old/CodeOpusC/Opus_B/Opus_B.skn",
"_old/CodeOpusC/Opus_D/Opus_D.skn",
"_old/CodeOpusC/Opus_DA/Opus_DA.skn",
"_old/CodeOpusC/Opus_G/Opus_G.skn",
"_old/Cyclops/1.Cyclops/1.Cyclops.skn",
"_old/dark_night/dark_night.skn",
"_old/Eyes/Eyes.skn",
"_old/falloutskn/falloutskn.skn",
"_old/first_skin/first_skin.skn",
"_old/Flyght/Flyght.skn",
"_old/gliteskin/gliteskin_deepsky/gliteskin_deepsky.skn",
"_old/gliteskin/gliteskin_red/gliteskin_red.skn",
"_old/gnome_style/gnome_blue/gnome_blue.skn",
"_old/gnome_style/gnome_green/gnome_green.skn",
"_old/gnome_style/gnome_ocean/gnome_ocean.skn",
"_old/gnome_style/gnome_olive/gnome_olive.skn",
"_old/gnome_style/gnome_orange/gnome_orange.skn",
"_old/gnome_style/gnome_red/gnome_red.skn",
"_old/Grey/Grey.skn",
"_old/humanoid_OSX/humanoid_OSX_blue/humanoid_OSX_blue.skn",
"_old/humanoid_OSX/Humanoid_OSX_dark_night/Humanoid_OSX_dark_night.skn",
"_old/humanoid_OSX/humanoid_OSX_green/humanoid_OSX_green.skn",
"_old/humanoid_OSX/humanoid_OSX_col/humanoid_OSX_col.skn",
"_old/khrome2/khrome2.skn",
"_old/Leency/Sandwich/Sandwich.skn",
"_old/lightskin/lightskin.skn",
"_old/macos_l/macos_l.skn",
"_old/mage-scroll/mage-scroll.skn",
"_old/MenuetOS/1.MenuetOS/MenuetOS 1.skn",
"_old/MenuetOS/3.MenuetOS/MenuetOS 3.skn",
"_old/MenuetOS/4.MenuetOS/MenuetOS 4.skn",
"_old/MenuetOS/5.MenuetOS/MenuetOS 5.skn",
"_old/MetalColor/MCBlue/MCBlue.skn",
"_old/MetalColor/MCRed/MCRed.skn",
"_old/mist/mist.skn",
"_old/mist_color/mist_color.skn",
"_old/mursky/mursky.skn",
"_old/MyTango/MyTango.skn",
"_old/Nature/Nature.skn",
"_old/neutral/neutral_blue/neutral_blue.skn",
"_old/neutral/neutral_green/neutral_green.skn",
"_old/neutral/neutral_lilac/neutral_lilac.skn",
"_old/nix/nix_small/nix_small.skn",
"_old/OpusOs_Blue/OpusOs_Blue.skn",
"_old/Organics/Organics.skn",
"_old/plum/plum.skn",
"_old/RoboTech/BRoboTech/BRoboTech.skn",
"_old/Sad_grey/Sad_grey.skn",
"_old/SashSkinPack_1_1/Src/Aqua/Aqua.skn",
"_old/SashSkinPack_1_1/Src/Cold/Cold.skn",
"_old/SashSkinPack_1_1/Src/Metal/Metal.skn",
"_old/sea/sea.skn",
"_old/Simple_gray/Simple_gray.skn",
"_old/skin_feol/skin_feol.skn",
"_old/skin_feol_new/skin_feol_new.skn",
"_old/skin_ser/skin_ser.skn",
"_old/skin_vhl/skin_vhl.skn",
"_old/sshock/sshock.skn",
"_old/StyleVista/vista/StyleVista_vista.skn",
"_old/StyleVista/vista_basic/vista_basic.skn",
"_old/StyleVista/vista_basic_black/vista_basic_black.skn",
"_old/StyleVista/vista_dark/vista_dark.skn",
"_old/StyleXP/orqua/orqua.skn",
"_old/StyleXP/panther/panther.skn",
"_old/StyleXP/wmpx/wmpx.skn",
"_old/subsilv/subsilv.skn",
"_old/Syllable/Syllable.skn",
"_old/testtest/testtest.skn",
"_old/USSR/USSR.skn",
"_old/USSR_2/1.USSR_2/1.USSR_2.skn",
"_old/WIN311/WIN311.skn",
"_old/win8/win8.skn",
"_old/WindowsXP/WinXP Classic blue/WinXP Classic blue.skn",
"_old/WindowsXP/WinXP Standard blue/WinXP Standard blue.skn",
"_old/WindowsXP/WinXP Standard olive_green/WinXP Standard olive_green.skn",
"_old/WindowsXP/WinXP Standard silver/WinXP Standard silver.skn",
"_old/zRiver/zRiver1/zRiver1.skn",
}
