-- Provides list of skins for distribution kit,
-- included by ../data/Tupfile.lua.
skinlist = {
"ConLenov/8Metro/8Metro.skn",
"ConLenov/Aigul/Aigul.skn",
"ConLenov/Guzel/Guzel.skn",
"ConLenov/Guzel_magic/Guzel_magic.skn",
"ConLenov/GX/GX_Red/GX_Red.skn",
"ConLenov/GX/GX_Violet/GX_Violet.skn",
"ConLenov/FlowerMoon/FlowerMoon.skn",
"ConLenov/Arina/Arina.skn",
"ConLenov/mntech/mntech.skn",
"ConLenov/LucidChocolate/LucidChocolate.skn",
"ConLenov/LucidCream/LucidCream.skn",
"ConLenov/Win10/Win10.skn",
"ConLenov/HotFox/HotFox.skn",
"dunkaist/mursky/mursky.skn",
"dunkaist/testtest/testtest.skn",
"Leency/AreaSq/AreaSq.skn",
"Leency/Florence/Florence.skn",
"Leency/HydrogenOS/HydrogenOS.skn",
"Leency/Oasis/Oasis.skn",
"Leency/ObsidianOS/ObsidianOS.skn",
"Leency/Octo_flat/Octo_flat.skn",
"Leency/Shkvorka/Shkvorka.skn",
"Leency/Workbench/Workbench.skn",
"Leency/Yeah/Yeah.skn",
"maxcodehack/blacky/Blacky.skn",
"misc/feol/feol.skn",
"misc/loggy/loggy.skn",
"misc/night/night.skn",
"misc/subsilv/subsilv.skn",
"_old/5imple Alpha/2.5imple Alpha/Simple Alpha.skn",
"_old/black-glass/black-glass/black-glass.skn",
"_old/black-glass/black-glass_light/black-glass_light.skn",
"_old/Black_lace/2.Black_lace/Black_lace.skn",
"_old/OpusOs_D/Opus_D.skn",
"_old/Cyclops/1.Cyclops/1.Cyclops.skn",
"_old/dark_night/dark_night.skn",
"_old/Eyes/Eyes.skn",
"_old/falloutskn/falloutskn.skn",
"_old/first_skin/first_skin.skn",
"_old/gliteskin/gliteskin_deepsky/gliteskin_deepsky.skn",
"_old/gliteskin/gliteskin_red/gliteskin_red.skn",
"_old/gnome_style/gnome_green/gnome_green.skn",
"_old/Grey/Grey.skn",
"_old/humanoid_OSX/Humanoid_OSX_dark_night/Humanoid_OSX_dark_night.skn",
"_old/humanoid_OSX/humanoid_OSX_green/humanoid_OSX_green.skn",
"_old/humanoid_OSX/humanoid_OSX_col/humanoid_OSX_col.skn",
"_old/lightskin/lightskin.skn",
"_old/macos_l/macos_l.skn",
"_old/mage-scroll/mage-scroll.skn",
"_old/MenuetOS/1.MenuetOS/MenuetOS 1.skn",
"_old/MenuetOS/5.MenuetOS/MenuetOS 5.skn",
"_old/MetalColor/MCBlue/MCBlue.skn",
"_old/MetalColor/MCRed/MCRed.skn",
"_old/nix/nix.skn",
"_old/OpusOs_Blue/OpusOs_Blue.skn",
"_old/Sad_grey/Sad_grey.skn",
"_old/Simple_gray/Simple_gray.skn",
"_old/skin_feol/skin_feol.skn",
"_old/skin_ser/skin_ser.skn",
"_old/skin_vhl/skin_vhl.skn",
"_old/StyleVista/vista_basic/vista_basic.skn",
"_old/StyleVista/vista_basic_black/vista_basic_black.skn",
"_old/StyleXP/orqua/orqua.skn",
"_old/StyleXP/panther/panther.skn",
"_old/USSR/USSR.skn",
"_old/USSR_2/1.USSR_2/USSR2.skn",
"_old/WIN311/WIN311.skn",
"_old/win8/win8.skn",
"_old/WindowsXP/WinXP Classic blue/WinXP Classic blue.skn",
"_old/WindowsXP/WinXP Standard blue/WinXP Standard blue.skn",
"_old/WindowsXP/WinXP Standard olive_green/WinXP Standard olive_green.skn",
"_old/WindowsXP/WinXP Standard silver/WinXP Standard silver.skn",
}
