-- Provides list of skins for distribution kit,
-- included by ../data/Tupfile.lua.
skinlist = {
"Leency/AreaSq/AreaSq.skn",
"Leency/Blueberries/Blueberries.skn",
"Leency/Latte/Latte.skn",
"Leency/Octo_flat/Octo_flat.skn",
"Leency/Shkvorka/Shkvorka.skn",
"Leency/Yeah/Yeah.skn",
"loggy/loggy.skn",
"night/night.skn",
"Win10/Win10.skn",
"_old/5imple Alpha/1.5imple Alpha/1.5imple Alpha.skn",
"_old/5imple Alpha/2.5imple Alpha/2.5imple Alpha.skn",
"_old/5imple Alpha/3.5imple Alpha/3.5imple Alpha.skn",
"_old/bat/bat.skn",
"_old/black-glass/black-glass/black-glass.skn",
"_old/black-glass/black-glass_light/black-glass_light.skn",
"_old/blackskin/blackskin.skn",
"_old/Black_lace/1.Black_lace/1.Black_lace.skn",
"_old/Black_lace/2.Black_lace/2.Black_lace.skn",
"_old/Blended/Blended.skn",
"_old/Brick/1.Brick/1.Brick.skn",
"_old/BrownLustre/BrownLustre/BrownLustre.skn",
"_old/BrownLustre/BrownLustre_2/BrownLustre_2.skn",
"_old/cherry/cherry.skn",
"_old/Circles/1.Circles/1.Circles.skn",
"_old/Circles/2.Circles/2.Circles.skn",
"_old/Circles/3.Circles/3.Circles.skn",
"_old/Circles/4.Circles/4.Circles.skn",
"_old/CodeOpusC/Opus_A/Opus_A.skn",
"_old/CodeOpusC/Opus_B/Opus_B.skn",
"_old/CodeOpusC/Opus_D/Opus_D.skn",
"_old/CodeOpusC/Opus_DA/Opus_DA.skn",
"_old/CodeOpusC/Opus_G/Opus_G.skn",
"_old/Crystal/Crystal.skn",
"_old/Cyclops/1.Cyclops/1.Cyclops.skn",
"_old/Cyclops/2.Cyclops/2.Cyclops.skn",
"_old/Dark_future/Dark_future.skn",
"_old/dark_night/dark_night.skn",
"_old/Devil_skins/Blue_devil/Blue_devil.skn",
"_old/Devil_skins/Green_devil/Green_devil.skn",
"_old/Devil_skins/Pink_devil/Pink_devil.skn",
"_old/Devil_skins/Red_devil/Red_devil.skn",
"_old/Devil_skins/Violet_devil/Violet_devil.skn",
"_old/Eyes/Eyes.skn",
"_old/falloutskn/falloutskn.skn",
"_old/Fever/Fever1 blue/Fever1 blue.skn",
"_old/Fever/Fever1 green/Fever1 green.skn",
"_old/Fever/Fever1 red/Fever1 red.skn",
"_old/Fever/Fever2 blue/Fever2 blue.skn",
"_old/Fever/Fever2 green/Fever2 green.skn",
"_old/Fever/Fever2 red/Fever2 red.skn",
"_old/first_skin/first_skin.skn",
"_old/Flowers/Flowers.skn",
"_old/Flyght/Flyght.skn",
"_old/Glass_lime/Glass_lime.skn",
"_old/gliteskin/gliteskin_deepsky/gliteskin_deepsky.skn",
"_old/gliteskin/gliteskin_glider/gliteskin_glider.skn",
"_old/gliteskin/gliteskin_red/gliteskin_red.skn",
"_old/gnome_style/gnome_blue/gnome_blue.skn",
"_old/gnome_style/gnome_green/gnome_green.skn",
"_old/gnome_style/gnome_ocean/gnome_ocean.skn",
"_old/gnome_style/gnome_olive/gnome_olive.skn",
"_old/gnome_style/gnome_orange/gnome_orange.skn",
"_old/gnome_style/gnome_red/gnome_red.skn",
"_old/Grey/Grey.skn",
"_old/Hearts/Hearts 3d/Hearts 3d.skn",
"_old/Hearts/Hearts flat/Hearts flat.skn",
"_old/humanoid_OSX/humanoid_OSX_blue/humanoid_OSX_blue.skn",
"_old/humanoid_OSX/Humanoid_OSX_dark/Humanoid_OSX_dark.skn",
"_old/humanoid_OSX/Humanoid_OSX_dark_night/Humanoid_OSX_dark_night.skn",
"_old/humanoid_OSX/humanoid_OSX_green/humanoid_OSX_green.skn",
"_old/humanoid_OSX/humanoid_OSX_orange/humanoid_OSX_orange.skn",
"_old/humanoid_OSX/humanoid_OSX_red/humanoid_OSX_red.skn",
"_old/humanoid_OSX/humanoid_OSX_yellow/humanoid_OSX_yellow.skn",
"_old/khrome2/khrome2.skn",
"_old/Leency/Luna/Luna.skn",
"_old/Leency/Octo/Octo.skn",
"_old/Leency/Sandwich/Sandwich.skn",
"_old/lightskin/lightskin.skn",
"_old/macos_l/macos_l.skn",
"_old/mage-scroll/mage-scroll.skn",
"_old/mage-slot/mage-slot.skn",
"_old/mage-teckno/mage-teckno.skn",
"_old/MenuetOS/1.MenuetOS/2/1.MenuetOS.2.skn",
"_old/MenuetOS/2.MenuetOS/1/2.MenuetOS.1.skn",
"_old/MenuetOS/2.MenuetOS/2/2.MenuetOS.2.skn",
"_old/MenuetOS/3.MenuetOS/1/3.MenuetOS.1.skn",
"_old/MenuetOS/3.MenuetOS/2/3.MenuetOS.2.skn",
"_old/MenuetOS/4.MenuetOS/1/4.MenuetOS.1.skn",
"_old/MenuetOS/4.MenuetOS/2/4.MenuetOS.2.skn",
"_old/MenuetOS/5.MenuetOS/1/5.MenuetOS.1.skn",
"_old/MenuetOS/5.MenuetOS/2/5.MenuetOS.2.skn",
"_old/MetalColor/MCBlue/MCBlue.skn",
"_old/MetalColor/MCRed/MCRed.skn",
"_old/MetalGearArrows/1.MetalGearArrows/1.MetalGearArrows.skn",
"_old/MetalGearArrows/2.MetalGearArrows/2.MetalGearArrows.skn",
"_old/MetalGearArrows/3.MetalGearArrows/3.MetalGearArrows.skn",
"_old/MetalGearArrows/4.MetalGearArrows/4.MetalGearArrows.skn",
"_old/mist/mist.skn",
"_old/mist_color/mist_color.skn",
"_old/mursky/mursky.skn",
"_old/mygrey/mygrey.skn",
"_old/myskin1/myskin1.skn",
"_old/myskin2/myskin2.skn",
"_old/myskin3/myskin3.skn",
"_old/myskin4/myskin4.skn",
"_old/MyTango/MyTango.skn",
"_old/Nature/Nature.skn",
"_old/neutral/neutral/neutral.skn",
"_old/neutral/neutral_blue/neutral_blue.skn",
"_old/neutral/neutral_green/neutral_green.skn",
"_old/neutral/neutral_lilac/neutral_lilac.skn",
"_old/nix/nix_big/nix_big.skn",
"_old/nix/nix_medium/nix_medium.skn",
"_old/nix/nix_small/nix_small.skn",
"_old/Nova_skins/Nova_blue/Nova_blue.skn",
"_old/Nova_skins/Nova_brown/Nova_brown.skn",
"_old/Nova_skins/Nova_green/Nova_green.skn",
"_old/Nova_skins/Nova_grey/Nova_grey.skn",
"_old/Nova_skins/Nova_pink/Nova_pink.skn",
"_old/Nova_skins/Nova_red/Nova_red.skn",
"_old/Nova_skins/Nova_violet/Nova_violet.skn",
"_old/OpusOs_Blue/OpusOs_Blue.skn",
"_old/Orange_aureole/Orange_aureole.skn",
"_old/Orange_Silence/Orange_Silence.skn",
"_old/Organics/Organics.skn",
"_old/panther/panther.skn",
"_old/plum/plum.skn",
"_old/Rednex/Rednex.skn",
"_old/RoboTech/BRoboTech/BRoboTech.skn",
"_old/RoboTech/GRoboTech/GRoboTech.skn",
"_old/Russia/Russia.skn",
"_old/Sad_grey/Sad_grey.skn",
"_old/SashSkinPack_1_1/Src/Aqua/Aqua.skn",
"_old/SashSkinPack_1_1/Src/Cold/Cold.skn",
"_old/SashSkinPack_1_1/Src/Metal/Metal.skn",
"_old/sea/sea.skn",
"_old/Simple_gray/Simple_gray.skn",
"_old/skin_feol/skin_feol.skn",
"_old/skin_feol_new/skin_feol_new.skn",
"_old/skin_ser/skin_ser.skn",
"_old/skin_vhl/skin_vhl.skn",
"_old/sshock/sshock.skn",
"_old/stone/stone.skn",
"_old/StyleVista/vista/StyleVista_vista.skn",
"_old/StyleVista/vista_basic/vista_basic.skn",
"_old/StyleVista/vista_basic_black/vista_basic_black.skn",
"_old/StyleVista/vista_dark/vista_dark.skn",
"_old/StyleXP/orqua/orqua.skn",
"_old/StyleXP/panther/StyleXP_panther.skn",
"_old/StyleXP/wmpx/wmpx.skn",
"_old/subsilv/subsilv.skn",
"_old/Syllable/Syllable.skn",
"_old/testtest/testtest.skn",
"_old/USSR/USSR.skn",
"_old/USSR_2/1.USSR_2/1.USSR_2.skn",
"_old/USSR_2/2.USSR_2/2.USSR_2.skn",
"_old/Victory_1945/Victory_1945.skn",
"_old/vista/vista.skn",
"_old/WIN311/WIN311.skn",
"_old/win8/win8.skn",
"_old/WindowsXP/WinXP Classic black/WinXP Classic black.skn",
"_old/WindowsXP/WinXP Classic blue/WinXP Classic blue.skn",
"_old/WindowsXP/WinXP Classic green/WinXP Classic green.skn",
"_old/WindowsXP/WinXP Classic orange/WinXP Classic orange.skn",
"_old/WindowsXP/WinXP Classic pink/WinXP Classic pink.skn",
"_old/WindowsXP/WinXP Classic red/WinXP Classic red.skn",
"_old/WindowsXP/WinXP Classic violet/WinXP Classic violet.skn",
"_old/WindowsXP/WinXP Classic yellow/WinXP Classic yellow.skn",
"_old/WindowsXP/WinXP Standard blue/WinXP Standard blue.skn",
"_old/WindowsXP/WinXP Standard olive_green/WinXP Standard olive_green.skn",
"_old/WindowsXP/WinXP Standard silver/WinXP Standard silver.skn",
"_old/winflat/winflat.skn",
"_old/zRiver/zRiver1/zRiver1.skn",
"_old/zRiver/zRiver2/zRiver2.skn",
"_old/zRiver/zRiver3/zRiver3.skn",
"_old/zRiver/zRiver4/zRiver4.skn",
"_old/zRiver/zRiver5/zRiver5.skn",
"_old/zRiver/zRiver6/zRiver6.skn",
}
