THIS_SRCS = abort.c abs.c atexit.c atof.c atoi.c atol.c atold.c bsearch.c \
	calloc.c div.c exit.c getenv.c labs.c ldiv.c malloc.c qsort.c \
	rand.c strtod.c strtol.c strtold.c strtoul.c system.c

include $(MENUET_LIBC_TOPDIR)/Make.rules
