OUTFILE = noout
OBJS = freebios.o
CFLAGS = -Os -DNOTPSP -DFRAMELIMIT -DNODEBUG -DNO_SNPRINTF -DKOLIBRI -I/home/hatsune/menuetos/include/SDL
LIBS = -lm
include $(MENUETDEV)/makefiles/Makefile_for_program
