amd:
file 'amd.gif'	     ;include gif file

cyrix:
file 'cyrix.gif'       ;include gif file

idt:
file 'idt.gif'	     ;include gif file

intel:
file 'intel.gif'       ;include gif file

transmeta:
file 'transmet.gif'	  ;include gif file

via:
file 'via.gif'		  ;include gif file

vortex:
file 'vortex.gif'	     ;include gif file

knopka:
file 'knopka.gif'	     ;include gif file

knopka2:
file 'knopka2.gif'		;gif button Save in file