THIS_SRCS = _chmod.c _close.c _creat.c crlf2nl.c dosio.c doslock.c \
	dosunloc.c fmode.c lock.c _open.c putpath.c _read.c setmode.c \
	tell.c unlock.c _write.c

include $(MENUET_LIBC_TOPDIR)/Make.rules

