# Sources
OBJS := api.o util.o generic.o 32bpp-xrgb8888.o 32bpp-xbgr8888.o 16bpp.o 8bpp.o

OUTFILE = libo.o

CFLAGS += -I ../../include/ -I ../../ -I ../ -I ./ -I /home/sourcerer/kos_src/newenginek/kolibri/include
include $(MENUETDEV)/makefiles/Makefile_for_o_lib
