//FIle listing generated by BAT script 
#define FILE_NAME_0 "KingsBounty/256.CC\0" 
dword file0 = FROM FILE_NAME_0;  
#define FILE_NAME_1 "KingsBounty/416.CC\0" 
dword file1 = FROM FILE_NAME_1;  
#define FILE_NAME_2 "KingsBounty/A.DAT\0" 
dword file2 = FROM FILE_NAME_2;  
#define FILE_NAME_3 "KingsBounty/ANDELOCK.DAT\0" 
dword file3 = FROM FILE_NAME_3;  
#define FILE_NAME_4 "KingsBounty/ANDREAS.DAT\0" 
dword file4 = FROM FILE_NAME_4;  
#define FILE_NAME_5 "KingsBounty/ANDY_OG_.DAT\0" 
dword file5 = FROM FILE_NAME_5;  
#define FILE_NAME_6 "KingsBounty/BENT.DAT\0" 
dword file6 = FROM FILE_NAME_6;  
#define FILE_NAME_7 "KingsBounty/E.DAT\0" 
dword file7 = FROM FILE_NAME_7;  
#define FILE_NAME_8 "KingsBounty/KB.EXE\0" 
dword file8 = FROM FILE_NAME_8;  
#define FILE_NAME_9 "KingsBounty/PLAY.sh\0" 
dword file9 = FROM FILE_NAME_9;  
