THIS_SRCS = d_close.c d_commit.c d_creat.c d_creatn.c d_exterr.c d_findf.c \
	d_findn.c d_getdat.c d_getdf.c d_getdrv.c d_getfa.c d_getftm.c \
	d_gettim.c d_open.c d_read.c d_setdat.c d_setdrv.c d_setfa.c d_setftm.c \
	d_settim.c d_write.c

include $(MENUET_LIBC_TOPDIR)/Make.rules
