THIS_SRCS = allocfil.c clearerr.c doprnt.c doscan.c fclose.c feof.c \
	ferror.c fflush.c fgetc.c fgetpos.c fgets.c filbuf.c flsbuf.c \
	fopen.c fprintf.c fputc.c fputs.c fread.c freopen.c frlist.c \
	fscanf.c fseek.c fsetpos.c ftell.c fwalk.c fwrite.c getc.c getchar.c \
	gets.c getw.c perror.c printf.c putc.c putchar.c puts.c putw.c \
	remove.c _rename.c rename.c rewind.c scanf.c setbuf.c setbuffe.c \
	setlineb.c setvbuf.c sprintf.c sscanf.c stdaux.c stderr.c stdin.c \
	stdiohk.c stdout.c stdprn.c tmpfile.c tmpnam.c ungetc.c vfprintf.c \
	vprintf.c vsprintf.c

include $(MENUET_LIBC_TOPDIR)/Make.rules
