# Sources
OBJS := \
	string.o node.o \
	attr.o characterdata.o element.o \
	implementation.o \
	text.o typeinfo.o comment.o \
	namednodemap.o nodelist.o \
	cdatasection.o document_type.o entity_ref.o pi.o \
	doc_fragment.o document.o 


OUTFILE = libo.o

CFLAGS += -I ../../include/ -I ../../ -I ../ -I ./ -I /home/sourcerer/kos_src/newenginek/kolibri/include -I ../../../libwapcaplet/include/ -I ../../../libparserutils/include/
include $(MENUETDEV)/makefiles/Makefile_for_o_lib
