fasm __lib__.asm
fasm sample_symbol.asm
fasm option_box_mouse.asm
fasm scrollbar_v_draw.asm
fasm scrollbar_v_mouse.asm
fasm scrollbar_h_draw.asm
fasm scrollbar_h_mouse.asm
fasm dbutton_draw.asm
fasm dbutton_mouse.asm
fasm menu_bar_draw.asm
fasm menu_bar_mouse.asm
fasm menu_bar_activate.asm
fasm FileBrowser_draw.asm
fasm FileBrowser_mouse.asm
fasm FileBrowser_key.asm
fasm tl_data_init.asm
fasm tl_data_clear.asm
fasm tl_info_clear.asm
fasm tl_key.asm
fasm tl_mouse.asm
fasm tl_draw.asm
fasm tl_info_undo.asm
fasm tl_info_redo.asm
fasm tl_node_add.asm
fasm tl_node_set_data.asm
fasm tl_node_get_data.asm
fasm tl_node_delete.asm
fasm tl_cur_beg.asm
fasm tl_cur_next.asm
fasm tl_cur_perv.asm
fasm tl_node_close_open.asm
fasm tl_node_lev_inc.asm
fasm tl_node_lev_dec.asm
fasm tl_node_move_up.asm
fasm tl_node_move_down.asm
fasm tl_node_poi_get_info.asm
fasm tl_node_poi_get_next_info.asm
fasm tl_node_poi_get_data.asm
fasm tl_save_mem.asm
fasm tl_load_mem.asm
fasm tl_get_mem_size.asm
fasm PathShow_prepare.asm
fasm PathShow_draw.asm
fasm ted_but_sumb_upper.asm
fasm ted_but_sumb_lover.asm
fasm ted_but_convert_by_table.asm
fasm ted_can_save.asm
fasm ted_clear.asm
fasm ted_delete.asm
fasm ted_draw.asm
fasm ted_init.asm
fasm ted_init_scroll_bars.asm
fasm ted_init_syntax_file.asm
fasm ted_is_select.asm
fasm ted_key.asm
fasm ted_mouse.asm
fasm ted_open_file.asm
fasm ted_save_file.asm
fasm ted_text_add.asm
fasm ted_but_select_word.asm
fasm ted_but_cut.asm
fasm ted_but_copy.asm
fasm ted_but_paste.asm
fasm ted_but_undo.asm
fasm ted_but_redo.asm
fasm ted_but_reverse.asm
fasm ted_but_find.asm
fasm ted_but_replace.asm
fasm ted_text_colored.asm
fasm ted_go_to_position.asm
fasm frame_draw.asm
fasm progressbar_draw.asm
fasm progressbar_progress.asm
kos32-ar -ru libbox_lib.a *.o
del *.o
pause