all:
	make -C bsd
	make -C io
	make -C math
	make -C mman
	make -C mntent
	make -C search
	make -C stdio
	make -C stdlib
	make -C string
	make -C sys
	make -C time
	make -C unistd
	make -C v1
	make -C signal
	make -C termios

clean:
	make -C bsd clean
	make -C io clean
	make -C math clean
	make -C mman clean
	make -C mntent clean
	make -C search clean
	make -C stdio clean
	make -C stdlib clean
	make -C string clean
	make -C sys clean
	make -C time clean
	make -C unistd clean
	make -C v1 clean
	make -C signal clean
	make -C termios clean

depend:
	make -C bsd depend
	make -C io depend
	make -C math depend
	make -C mman depend
	make -C mntent depend
	make -C search depend
	make -C stdio depend
	make -C stdlib depend
	make -C string depend
	make -C sys depend
	make -C time depend
	make -C unistd depend
	make -C v1 depend
	make -C signal depend
	make -C termios depend
