CPPFLAGS= -m32 -fpack-struct=2 -fno-exceptions -std=c++03 -Wno-write-strings -Dstricmp=strcasecmp -Dstrnicmp=strncasecmp -DO_BINARY=0 -D_UNIX_
LDFLAGS=  -m32 -static

OBJS=$(patsubst %.cpp, %.o, $(wildcard *.cpp))

TARGET = c--

$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) $^ -o $@

%.o: %.cpp
	$(CC) $(CPPFLAGS) -c $<

clean:
	rm -f $(OBJS) $(TARGET)

install: $(TARGET)
	cp c-- ../../cmm/c--/c--.elf
