CPPFLAGS=-m32 -fpack-struct=2 -fno-exceptions -std=c++03 -Wno-write-strings -D_WIN32_
LDFLAGS=-m32

OBJS=$(patsubst %.cpp, %.o, $(wildcard *.cpp))

c--.exe: $(OBJS)
	g++ $^ -o $@

%.o: %.cpp
	g++ $(CPPFLAGS) -c $<
