all:
	make -C dirent
	make -C fcntl
	make -C fnmatch
	make -C glob
	make -C grp
	make -C pwd
	make -C regex
	make -C setjmp
	make -C signal
	make -C stdio
	make -C sys
	make -C unistd
	make -C utime
	make -C utsname

clean:
	make -C dirent clean
	make -C fcntl clean
	make -C fnmatch clean
	make -C glob clean
	make -C grp clean
	make -C pwd clean
	make -C regex clean
	make -C setjmp clean
	make -C signal clean
	make -C stdio clean
	make -C sys clean
	make -C unistd clean
	make -C utime clean
	make -C utsname clean

depend:
	make -C dirent depend
	make -C fcntl depend
	make -C fnmatch depend
	make -C glob depend
	make -C grp depend
	make -C pwd depend
	make -C regex depend
	make -C setjmp depend
	make -C signal depend
	make -C stdio depend
	make -C sys depend
	make -C unistd depend
	make -C utime depend
	make -C utsname depend
