#define	FLAG_SCROLL_BAR_ORIENTATION_HORIZONTAL_ON		0x1
#define	FLAG_SCROLL_BAR_ORIENTATION_HORIZONTAL_OFF	0xfe
#define	FLAG_SCROLL_BAR_ORIENTATION_VERTICAL_ON		0x2
#define	FLAG_SCROLL_BAR_ORIENTATION_VERTICAL_OFF		0xfd
#define	FLAG_SCROLL_RULLER_PRESSED				0x4
#define	FLAG_SCROLL_RULLER_RELEASED				0xfb
