#define	FLAG_PB_VERTICAL_ORIENTATION_ON		0x1
#define	FLAG_PB_HORIZONTAL_ORIENTATION_ON	0x2
#define	FLAG_PB_FROM_LEFT_TO_RIGHT_ON		0x4
#define	FLAG_PB_FROM_RIGHT_TO_LEFT_ON		0x8
#define	FLAG_PB_FROM_DOWN_TO_UP_ON			0x10
#define	FLAG_PB_FROM_UP_TO_DOWN_ON			0x20
#define FLAG_PB_TEXT_ON						0x40

#define	FLAG_PB_VERTICAL_ORIENTATION_OFF	0xfe
#define	FLAG_PB_HORIZONTAL_ORIENTATION_OFF	0xfd
#define	FLAG_PB_FROM_LEFT_TO_RIGHT_OFF		0xfb
#define	FLAG_PB_FROM_RIGHT_TO_LEFT_OFF		0xf7
#define	FLAG_PB_FROM_DOWN_TO_UP_OFF			0xef
#define	FLAG_PB_FROM_UP_TO_DOWN_OFF			0xdf
#define FLAG_PB_TEXT_OFF					0xbf

