# This is not a independent Makefile; it is auxiliary file
# included from main Makefile.

# The arguments of macro pestrip_meta_rule:
# $(1) = name of stripped file,
# $(2) = name of input file
define pestrip_meta_rule
$(1): $(2) Makefile.pestrip
	EXENAME="$$<" fasm ../common/pestrip.asm "$$@"
	kpack --nologo "$$@"
endef
