
OUTFILE = libo.o
OBJS = parse.o language.o important.o propstrings.o font_face.o
CFLAGS += -I ../../include/ -I ../../../ -I ../ -I /home/sourcerer/kos_src/newenginek/kolibri/include
include $(MENUETDEV)/makefiles/Makefile_for_o_lib
