
OUTFILE = libo.o
OBJS = computed.o dispatch.o hash.o select.o font_face.o
CFLAGS += -I ../../include/ -I ../../../ -I ../ -I /home/sourcerer/kos_src/newenginek/kolibri/include -I ../../../libwapcaplet/include/ -I ../../../libparserutils/include/
include $(MENUETDEV)/makefiles/Makefile_for_o_lib
