THIS_SRCS = backgr.c bar.c button.c clock.c date.c delay.c dga.c \
	event.c exit.c file.c image.c ipc.c irq.c keyb.c line.c \
	mpu401.c param.c pixel.c process.c screen.c sound.c systree.c \
	text.c thread.c window.c pci.c alloca.s cofflib.c debug.c

include $(MENUET_LIBC_TOPDIR)/Make.rules

