/* utils/testament.h
 * 
 * Revision testament.
 *
 * *WARNING* this file is automatically generated by git-testament.pl 
 *
 * Copyright 2012 NetSurf Browser Project
 */

#ifndef NETSURF_REVISION_TESTAMENT
#define NETSURF_REVISION_TESTAMENT "178a6caf6b7896579100426d2e86272e"

/* Revision testament checksum:
 * MD5:178a6caf6b7896579100426d2e86272e
 */

/* Revision testament: */
#define USERNAME "sourcerer"
#define GECOS "sourcerer"
#define WT_ROOT "/home/sourcerer/kos_src/netsurf/unix/netsurf/"
#define WT_HOSTNAME "debian"
#define WT_COMPILEDATE "04.02.2013"
#define WT_BRANCHPATH "master"
#define WT_BRANCHISMASTER 1
#define WT_REVID "43fe4490d3152ccecd7fd8065c09faaa893fb09e"
#define WT_MODIFIED 11
#define WT_MODIFICATIONS {\
  { "buildsystem/", "??" }, \
  { "libcss/", "??" }, \
  { "libdom/", "??" }, \
  { "libhubbub/", "??" }, \
  { "libmng-1.0.10/", "??" }, \
  { "libnsbmp/", "??" }, \
  { "libnsfb/", "??" }, \
  { "libnsgif/", "??" }, \
  { "libparserutils/", "??" }, \
  { "libwapcaplet/", "??" }, \
  { "nsgenbind", "??" } \
}

#endif
