OUTFILE = libo.o
OBJS = codec_ascii.o codec_8859.o codec_ext8.o \
	codec_utf8.o codec_utf16.o
CFLAGS += -I ../../../include/ -I ../../../../ -I ../../
include $(MENUETDEV)/makefiles/Makefile_for_o_lib
