#include<stdio.h>

int a,b,c;

int main(void)
{
 fscanf(stdin,"%u.%u.%u",&a,&b,&c);
 fprintf(stdout,"/* This file is automatically generated by mkversion. */\n");
 fprintf(stdout,"/* Please do not modify it unless you know what you are doing. */\n");
 fprintf(stdout,"#define MENUET_LIBC_VERSION \"%u.%u.%u\"\n",a,b,c);
 fprintf(stdout,"\n#ifdef INCLUDE_RCS_ID\n");
 fprintf(stdout,"static const char * ___menuet__libc_version_%u_%u_%u=\"",a,b,c);
 fprintf(stdout,"MenuetOS GNU C library port by Jarek Pelczar. This file is \" __FILE__ ; \n");
 fprintf(stdout,"#endif\n");
 return 0;
}
