# Sources
OBJS := parser.o


OUTFILE = libo.o

CFLAGS += -I ./ -I ../../include/ -I ../../src/ -I ../../../libhubbub/include/ -I ../../../libwapcaplet/include/
include $(MENUETDEV)/makefiles/Makefile_for_o_lib
