# This is the makefile in kolibrios/contrib/network/netsurf/libnsgif/
# Need to add recursive calling to all the subdirectories. For now, use the generated .a file for testing.

OUTFILE := $(CURDIR)/libnsgif.a

OBJS = $(wildcard src/*.o)

include $(MENUETDEV)/makefiles/Makefile_for_lib
