THIS_SRCS = memchr.c memcmp.c memcpy.c memmove.s memset.s strcat.c \
	strchr.c strcmp.c strcoll.c strcpy.c strcspn.c strerror.c \
	strlen.c strncat.c strncmp.c strncpy.c strpbrk.c strrchr.c \
	strspn.c strstr.c strtok.c strxfrm.c syserr1.c syserr2.c syserr3.c

include $(MENUET_LIBC_TOPDIR)/Make.rules
